# This only checks the c part of the repository, it was difficult to
# get the Python bindings to build on 

language: c
git:
  depth: 3
dist:
  trusty

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq check
  - pip install --user cython 

branches:
  only:
    - master
    - dev

compiler:
  - gcc
  - clang

before_script:
  - autoreconf -i
  - ./configure --enable-check CFLAGS="-fPIC -O2" --enable-python-bindings

script: make && make check
