# This only checks the c part of the repository, it was difficult to
# get the Python bindings to build on 

language: c
git:
  depth: 3
dist:
  trusty

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq check
  - pip install --user cpp-coveralls  
#  - pip install --user cython # doesn't work for some reason

branches:
  only:
    - master
    - dev

compiler:
  - gcc
  - clang

before_script:
  - autoreconf -i
  - ./configure --enable-check --enable-gcov CFLAGS="-fPIC -O2"

script: make && make check

after_success:
  - coveralls --exclude tests --exclude src/lexer.l --exclude src/lexer.c --exclude src/parser.c  --gcov-options '\-lp'

